# Generated by Django 5.1 on 2024-09-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('message', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'message_store',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ChatMessageHistory',
        ),
    ]
