# Generated by Django 5.1 on 2024-09-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_messagestore_delete_chatmessagehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageStore',
        ),
    ]
